'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("risersoft.unitcad.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to add the dynamic child rule &apos;{0}&apos;: {1}.
        '''</summary>
        Friend ReadOnly Property Error_AddDynamicChild() As String
            Get
                Return ResourceManager.GetString("Error_AddDynamicChild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error encountered while applying changes: {0}.
        '''</summary>
        Friend ReadOnly Property Error_ApplyChanges() As String
            Get
                Return ResourceManager.GetString("Error_ApplyChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some choices were not added to the list because they are not valid Intent names: .
        '''</summary>
        Friend ReadOnly Property PartEditor_ComboBoxWarning() As String
            Get
                Return ResourceManager.GetString("PartEditor_ComboBoxWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Caught exception from custom part editor control during Refresh call:
        '''{0}.
        '''</summary>
        Friend ReadOnly Property PartEditor_CustomRefreshException() As String
            Get
                Return ResourceManager.GetString("PartEditor_CustomRefreshException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specified class, &apos;{0}&apos;, does not implement IPartEditorControl..
        '''</summary>
        Friend ReadOnly Property PartEditor_DoesNotImplementIPartEditorControl() As String
            Get
                Return ResourceManager.GetString("PartEditor_DoesNotImplementIPartEditorControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception caught loading control {0}. 
        '''
        '''{1}.
        '''</summary>
        Friend ReadOnly Property PartEditor_ErrorLoadingControl() As String
            Get
                Return ResourceManager.GetString("PartEditor_ErrorLoadingControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to get type information for &apos;{0}&apos;..
        '''</summary>
        Friend ReadOnly Property PartEditor_GetTypeFailed() As String
            Get
                Return ResourceManager.GetString("PartEditor_GetTypeFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to load xaml component &apos;{0}&apos;. 
        '''
        '''Check to ensure the Assembly exists and the class is derived from FrameworkElement..
        '''</summary>
        Friend ReadOnly Property PartEditor_LoadComponentFailed() As String
            Get
                Return ResourceManager.GetString("PartEditor_LoadComponentFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}{0}Please fix the parse error:{0}Row: {1}{0}Column: {2}.
        '''</summary>
        Friend ReadOnly Property PartEditor_ParseError() As String
            Get
                Return ResourceManager.GetString("PartEditor_ParseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error opening the Select File dialog: {0}.
        '''</summary>
        Friend ReadOnly Property PartEditor_SelectFileError() As String
            Get
                Return ResourceManager.GetString("PartEditor_SelectFileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a file.
        '''</summary>
        Friend ReadOnly Property PartEditor_SelectFileTitle() As String
            Get
                Return ResourceManager.GetString("PartEditor_SelectFileTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a folder.
        '''</summary>
        Friend ReadOnly Property PartEditor_SelectFolderDescription() As String
            Get
                Return ResourceManager.GetString("PartEditor_SelectFolderDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error opening the Select Folder dialog: {0}.
        '''</summary>
        Friend ReadOnly Property PartEditor_SelectFolderError() As String
            Get
                Return ResourceManager.GetString("PartEditor_SelectFolderError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: &apos;{1}&apos; at position {2} in &apos;{3}&apos;.
        '''</summary>
        Friend ReadOnly Property PartEditor_SyntaxError() As String
            Get
                Return ResourceManager.GetString("PartEditor_SyntaxError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intent Part Editor.
        '''</summary>
        Friend ReadOnly Property PartEditor_Title() As String
            Get
                Return ResourceManager.GetString("PartEditor_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid name - name cannot contain embedded spaces.
        '''</summary>
        Friend ReadOnly Property PartNameInvalid_EmbeddedSpaces() As String
            Get
                Return ResourceManager.GetString("PartNameInvalid_EmbeddedSpaces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid name - name cannot be empty.
        '''</summary>
        Friend ReadOnly Property PartNameInvalid_Empty() As String
            Get
                Return ResourceManager.GetString("PartNameInvalid_Empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid name.
        '''</summary>
        Friend ReadOnly Property PartNameInvalid_Generic() As String
            Get
                Return ResourceManager.GetString("PartNameInvalid_Generic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid name - one or more characters are not valid.
        '''</summary>
        Friend ReadOnly Property PartNameInvalid_InvalidCharacters() As String
            Get
                Return ResourceManager.GetString("PartNameInvalid_InvalidCharacters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid name - invalid first character.
        '''</summary>
        Friend ReadOnly Property PartNameInvalid_InvalidFirstCharacter() As String
            Get
                Return ResourceManager.GetString("PartNameInvalid_InvalidFirstCharacter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Part with this name already exists.
        '''</summary>
        Friend ReadOnly Property PartWithThisNameAlreadyExists() As String
            Get
                Return ResourceManager.GetString("PartWithThisNameAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ToggleCustomStandardPartEditor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ToggleCustomStandardPartEditor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
